name: Testing action when closing PR

on:
    pull_request:
        types: [closed]

jobs:
    hasOneOfLabel:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Checking correct labels
              id: correctLabels
              uses: netcreaties/has-one-of-label@main
              with:
                  labels: "patch,minor,major"
            - name: Checking incorrect labels
              id: incorrectLabels
              uses: netcreaties/has-one-of-label@main
              with:
                  optional: "yes"
                  labels: "pluto,mars,venus"
            - name: Validating correct label output
              run: bash ./.github/check-correct-labels.sh ${steps.correctLabels.outputs.matched} ${steps.correctLabels.outputs.found}
            - name: Validating incorrect label output
              run: bash ./.github/check-incorrect-labels.sh ${steps.correctLabels.outputs.found}
